version: "3.7"
services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.5.0
    container_name: rest-proxy
    hostname: rest-proxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_REST_HOST_NAME: "rest-proxy"
    networks:
      - kafka_default

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    container_name: kafka-topics-ui
    hostname: kafka-topics-ui
    ports:
      - "8002:8000"
    depends_on:
      - rest-proxy
    environment:
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
      PROXY: "true"
    networks:
      - kafka_default
networks:
  kafka_default:
    external: true
