version: "3.7"

services:
  wordcount:
    build: .
    container_name: wordcount
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      STREAMS_APPLICATION_ID: "wordcount"
      STREAMS_INPUT_TOPIC: "streams-plaintext-input"
      STREAMS_OUTPUT_TOPIC: "streams-wordcount-output"
    networks:
      - kafka_default

networks:
  kafka_default:
    external: true

