version: "3.7"
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.0
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:29092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_DEBUG: "true"
      # SCHEMA_REGISTRY_LISTENERS: "http://localhost:8081"
    networks:
      - kafka_default

  schema-registry-ui:
    image: landoop/schema-registry-ui
    container_name: schema-registry-ui
    hostname: schema-registry-ui
    ports:
      - "8001:8000"
    depends_on:
      - schema-registry
    environment:
      SCHEMAREGISTRY_URL: "http://schema-registry:8081"
      PROXY: "true"
    networks:
      - kafka_default
networks:
  kafka_default:
    external: true
