version: "3.7"
services:
  postgres:
    image: debezium/postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - kafka_default

  debezium-connect:
    image: debezium/connect:1.2
    container_name: debezium-connect
    hostname: debezium-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets
      STATUS_STORAGE_TOPIC: my-connect-statuses
    networks:
      - kafka_default

networks:
  kafka_default:
    external: true
