version: "3.7"
services:
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    hostname: akhq
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:29092"
              schema-registry:
                url: "http://schema-registry:8081"
    networks:
      - kafka_default

networks:
  kafka_default:
    external: true
