# kafka-docker/docker-compose.yml
version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://${ADVERTISED_HOST_NAME}:9093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SSL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1"
      KAFKA_SSL_KEYSTORE_LOCATION: /tmp/ssl/ssl_files/kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: serversecret
      KAFKA_SSL_KEY_PASSWORD: serversecret
      KAFKA_SSL_TRUSTSTORE_PASSWORD: serversecret
      KAFKA_SSL_TRUSTSTORE_LOCATION: /tmp/ssl/ssl_files/kafka.server.truststore.jks
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/krunalvora/personal/apachekafka101/kafka-security/ssl:/tmp/ssl
  