# kafka-docker/docker-compose.yml
version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL_PLAINTEXT://0.0.0.0:9092,EXTERNAL_SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:29092,EXTERNAL_PLAINTEXT://localhost:9092,EXTERNAL_SSL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1"
      # SSL Properties
      KAFKA_SSL_KEYSTORE_LOCATION: /tmp/server_keystores/kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: serversecret
      KAFKA_SSL_KEY_PASSWORD: serversecret
      KAFKA_SSL_TRUSTSTORE_PASSWORD: serversecret
      KAFKA_SSL_TRUSTSTORE_LOCATION: /tmp/server_keystores/kafka.server.truststore.jks
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/server_keystores:/tmp/server_keystores
  