version: "3.7"
services:
  zoonavigator:
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    ports:
      - "9000:9000"
    environment:
      AUTO_CONNECT_CONNECTION_STRING: "zookeeper:2181"
      HTTP_PORT: 9000
    networks:
      - kafka_default 
networks:
  kafka_default:
    external: true
