# kafka-docker/docker-compose.yml
version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: DOCKER_INTERNAL://kafka1:29092,DOCKER_HOST_MACHINE://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka1:29092,DOCKER_HOST_MACHINE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_HOST_MACHINE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: DOCKER_INTERNAL://kafka2:29092,DOCKER_HOST_MACHINE://kafka2:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka2:29092,DOCKER_HOST_MACHINE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_HOST_MACHINE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    container_name: kafka3
    hostname: kafka3
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: DOCKER_INTERNAL://kafka3:29092,DOCKER_HOST_MACHINE://kafka3:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka3:29092,DOCKER_HOST_MACHINE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_HOST_MACHINE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock