version: "3.7"
services:
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    hostname: akhq
    ports:
      - "8080:8080"
#    environment:
#      AKHQ_CONFIGURATION: |
#        akhq:
#          connections:
#            local-kafka:
#              properties:
#                bootstrap.servers: "kafka:29092"
#              schema-registry:
#                url: "http://schema-registry:8081"
    volumes:
      - /Users/krunalvora/personal/kafka-workshop/docker-compose/akhq/akhq.yml:/app/application.yml
    networks:
      - kafka_default

networks:
  kafka_default:
    external: true
